// ==========================================================================
// MODULE 1: questions.js
// Question Banks: 50 Questions for Each Subject (300 Questions Total)
// ==========================================================================

const subjectQuestions = {
  // MATHEMATICS (50 QUESTIONS)
  math: [
    { question: "What is the value of 15 × 4 + 10?", options: ["50", "70", "60", "80"], answer: 1 },
    { question: "What is the square root of 144?", options: ["10", "11", "12", "14"], answer: 2 },
    { question: "Solve for x: 2x + 6 = 18", options: ["x = 6", "x = 4", "x = 8", "x = 12"], answer: 0 },
    { question: "What is 25% of 200?", options: ["25", "40", "50", "75"], answer: 2 },
    { question: "How many degrees are in the sum of angles of a triangle?", options: ["90°", "180°", "270°", "360°"], answer: 1 },
    { question: "What is the next prime number after 7?", options: ["9", "10", "11", "13"], answer: 2 },
    { question: "What is the perimeter of a rectangle with length 8cm and width 4cm?", options: ["24cm", "32cm", "16cm", "28cm"], answer: 0 },
    { question: "Simplify: (5 + 3) × 2 - 4", options: ["10", "12", "14", "16"], answer: 1 },
    { question: "What is the value of 2 to the power of 5 (2⁵)?", options: ["16", "25", "32", "64"], answer: 2 },
    { question: "If a shirt costs $40 after a 20% discount, what was its original price?", options: ["$48", "$50", "$60", "$55"], answer: 1 },
    { question: "What is 7 cubed (7³)?", options: ["243", "343", "441", "349"], answer: 1 },
    { question: "What is the area of a square with side length 9cm?", options: ["18cm²", "36cm²", "72cm²", "81cm²"], answer: 3 },
    { question: "What is the greatest common divisor (GCD) of 12 and 18?", options: ["2", "3", "6", "9"], answer: 2 },
    { question: "What is the least common multiple (LCM) of 4 and 6?", options: ["12", "18", "24", "8"], answer: 0 },
    { question: "If x = 3 and y = 4, what is the value of x² + y²?", options: ["7", "12", "25", "49"], answer: 2 },
    { question: "What is 3/5 expressed as a percentage?", options: ["30%", "50%", "60%", "75%"], answer: 2 },
    { question: "How many sides does a heptagon have?", options: ["6", "7", "8", "9"], answer: 1 },
    { question: "What is the formula for the area of a circle?", options: ["2πr", "πr²", "πd", "2πr²"], answer: 1 },
    { question: "Solve for y: 5y - 15 = 0", options: ["y = 0", "y = 3", "y = 5", "y = -3"], answer: 1 },
    { question: "What is 100 divided by 0.5?", options: ["50", "100", "200", "500"], answer: 2 },
    { question: "What is the sum of the first 5 positive integers (1+2+3+4+5)?", options: ["10", "12", "15", "20"], answer: 2 },
    { question: "Convert 0.75 to a simple fraction:", options: ["1/2", "2/3", "3/4", "4/5"], answer: 2 },
    { question: "What is the Roman numeral for 50?", options: ["C", "D", "L", "V"], answer: 2 },
    { question: "What is the slope of a horizontal line?", options: ["0", "1", "Undefined", "-1"], answer: 0 },
    { question: "How many seconds are in 2.5 hours?", options: ["150", "3600", "7200", "9000"], answer: 3 },
    { question: "If 3 pens cost $15, how much will 7 pens cost?", options: ["$25", "$30", "$35", "$40"], answer: 2 },
    { question: "What is 15% of 80?", options: ["8", "10", "12", "14"], answer: 2 },
    { question: "Which of the following numbers is an irrational number?", options: ["√4", "3/4", "√2", "0.25"], answer: 2 },
    { question: "What is the supplementary angle of 70°?", options: ["20°", "90°", "110°", "130°"], answer: 2 },
    { question: "What is the complementary angle of 35°?", options: ["45°", "55°", "65°", "145°"], answer: 1 },
    { question: "What is the median of the numbers: 3, 7, 9, 12, 15?", options: ["7", "9", "9.2", "12"], answer: 1 },
    { question: "What is the mean of: 4, 8, 12, 16?", options: ["8", "9", "10", "12"], answer: 2 },
    { question: "What is 2³ × 3²?", options: ["36", "72", "64", "48"], answer: 1 },
    { question: "If a car travels 180 km in 3 hours, what is its average speed?", options: ["50 km/h", "60 km/h", "70 km/h", "90 km/h"], answer: 1 },
    { question: "Factorize: x² - 9", options: ["(x - 3)²", "(x + 3)(x - 3)", "(x + 9)(x - 1)", "(x - 9)(x + 1)"], answer: 1 },
    { question: "What is the reciprocal of 4/7?", options: ["-4/7", "7/4", "-7/4", "1/4"], answer: 1 },
    { question: "How many degrees are in a right angle?", options: ["45°", "90°", "180°", "360°"], answer: 1 },
    { question: "What is the value of (-5) × (-4)?", options: ["-20", "20", "-9", "9"], answer: 1 },
    { question: "What is 10 to the power of 0 (10⁰)?", options: ["0", "1", "10", "Undefined"], answer: 1 },
    { question: "How many millimeters are in 5.5 meters?", options: ["55mm", "550mm", "5500mm", "55000mm"], answer: 2 },
    { question: "What is the value of π (Pi) rounded to two decimal places?", options: ["3.12", "3.14", "3.16", "3.18"], answer: 1 },
    { question: "Solve: 4(x - 2) = 16", options: ["x = 4", "x = 6", "x = 8", "x = 2"], answer: 1 },
    { question: "What is the probability of flipping heads on a fair coin?", options: ["0.25", "0.5", "0.75", "1"], answer: 1 },
    { question: "What is the volume of a cube with side length 3cm?", options: ["9cm³", "18cm³", "27cm³", "36cm³"], answer: 2 },
    { question: "What is the simple interest on $1,000 at 5% per annum for 2 years?", options: ["$50", "$100", "$150", "$200"], answer: 1 },
    { question: "How many vertices does a cube have?", options: ["6", "8", "12", "14"], answer: 1 },
    { question: "What is the product of 11 and 12?", options: ["121", "131", "132", "142"], answer: 2 },
    { question: "What is 4! (4 factorial)?", options: ["10", "16", "24", "36"], answer: 2 },
    { question: "Which polygon has 10 sides?", options: ["Nonagon", "Decagon", "Dodecagon", "Octagon"], answer: 1 },
    { question: "If 2x = 50, what is x/5?", options: ["5", "10", "15", "25"], answer: 0 }
  ],

  // ENGLISH LANGUAGE (50 QUESTIONS)
  english: [
    { question: "Choose the correct spelling:", options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"], answer: 0 },
    { question: "What is the antonym (opposite) of 'Generous'?", options: ["Kind", "Selfish", "Friendly", "Honest"], answer: 1 },
    { question: "Identify the noun: 'The curious cat ran quickly.'", options: ["curious", "quickly", "cat", "ran"], answer: 2 },
    { question: "Choose the correct past tense of 'Drink':", options: ["Drunk", "Drank", "Drinked", "Drinking"], answer: 1 },
    { question: "What is the synonym of 'Ancient'?", options: ["Modern", "Recent", "Old", "Future"], answer: 2 },
    { question: "Complete the sentence: 'She has ______ finished her assignment.'", options: ["already", "all ready", "alright", "all right"], answer: 0 },
    { question: "What type of word is 'Quietly' in: 'She walked quietly'?", options: ["Adjective", "Adverb", "Verb", "Preposition"], answer: 1 },
    { question: "Which of the following is a metaphor?", options: ["He is as brave as a lion", "Time is money", "The wind whispered", "She cried buckets"], answer: 1 },
    { question: "Choose the correct plural form of 'Child':", options: ["Childs", "Childrens", "Children", "Childes"], answer: 2 },
    { question: "Which word is an interjection?", options: ["Wow!", "And", "Because", "Under"], answer: 0 },
    { question: "Select the correctly punctuated sentence:", options: ["Where are you going.", "Where are you going?", "Where are you going!", "Where are you going,"], answer: 1 },
    { question: "What is a group of lions called?", options: ["Pack", "Herd", "Flock", "Pride"], answer: 3 },
    { question: "What is the antonym of 'Transparent'?", options: ["Clear", "Opaque", "Bright", "Clean"], answer: 1 },
    { question: "Identify the conjunction in: 'I wanted to go, but it was raining.'", options: ["wanted", "go", "but", "was"], answer: 2 },
    { question: "Choose the correct pronoun: 'Neither of the boys brought ______ book.'", options: ["his", "their", "them", "they"], answer: 0 },
    { question: "What figure of speech gives human qualities to animals or objects?", options: ["Hyperbole", "Simile", "Personification", "Alliteration"], answer: 2 },
    { question: "Which of the following is a synonym for 'Abundant'?", options: ["Scarce", "Plentiful", "Little", "Rare"], answer: 1 },
    { question: "Choose the correct word: 'The sun will ______ in the east.'", options: ["rise", "raise", "rose", "rising"], answer: 0 },
    { question: "Identify the adjective in: 'The red car zoomed past.'", options: ["car", "red", "zoomed", "past"], answer: 1 },
    { question: "What is the comparative form of the adjective 'Good'?", options: ["Gooder", "Best", "Better", "More good"], answer: 2 },
    { question: "What is the superlative form of 'Bad'?", options: ["Worse", "Baddest", "Worst", "More bad"], answer: 2 },
    { question: "Choose the correct preposition: 'He is proficient ______ English.'", options: ["in", "at", "with", "on"], answer: 0 },
    { question: "Which sentence is written in the passive voice?", options: ["The chef cooked the meal.", "The meal was cooked by the chef.", "The chef is cooking.", "The chef will cook."], answer: 1 },
    { question: "What is an exaggeration used for emphasis called?", options: ["Irony", "Hyperbole", "Oxymoron", "Onomatopoeia"], answer: 1 },
    { question: "Choose the correct spelling:", options: ["Receive", "Recieve", "Receve", "Riceive"], answer: 0 },
    { question: "What is the plural form of 'Cactus'?", options: ["Cactuses", "Cacti", "Cacta", "Both A and B"], answer: 3 },
    { question: "What does the idiom 'Bite the bullet' mean?", options: ["To eat quickly", "To face a difficult situation with courage", "To shoot a gun", "To run away"], answer: 1 },
    { question: "Identify the prefix in the word 'Unhappy':", options: ["Un", "Happy", "Appy", "Hap"], answer: 0 },
    { question: "Identify the suffix in the word 'Careless':", options: ["Care", "Rel", "Less", "Ess"], answer: 2 },
    { question: "Choose the correct form: 'Each of the students ______ present.'", options: ["is", "are", "were", "have been"], answer: 0 },
    { question: "What is the antonym of 'Expand'?", options: ["Enlarge", "Contract", "Grow", "Extend"], answer: 1 },
    { question: "Choose the correct homophone: 'I cannot ______ this heavy weight.'", options: ["bare", "bear", "beer", "bier"], answer: 1 },
    { question: "What is a poem of fourteen lines called?", options: ["Ballad", "Sonnet", "Haiku", "Epic"], answer: 1 },
    { question: "What does the root word 'Bio' mean?", options: ["Earth", "Life", "Water", "Light"], answer: 1 },
    { question: "Choose the correct spelling:", options: ["Definately", "Definitely", "Definetly", "Definitaly"], answer: 1 },
    { question: "Identify the verb in: 'The birds sing beautifully every morning.'", options: ["birds", "sing", "beautifully", "morning"], answer: 1 },
    { question: "Which word means 'a person who writes plays'?", options: ["Playwriter", "Playwright", "Playwrite", "Playright"], answer: 1 },
    { question: "What is the synonym of 'Courageous'?", options: ["Timid", "Cowardly", "Brave", "Fearful"], answer: 2 },
    { question: "Complete: 'A stitch in time saves ______.'", options: ["five", "seven", "nine", "ten"], answer: 2 },
    { question: "What is the plural of 'Foot'?", options: ["Foots", "Feet", "Feets", "Footes"], answer: 1 },
    { question: "Which of the following is an example of an onomatopoeia?", options: ["Buzz", "Fast", "Quiet", "Bright"], answer: 0 },
    { question: "What does 'Omniscient' mean?", options: ["All-powerful", "All-knowing", "Ever-present", "Invisible"], answer: 1 },
    { question: "Choose the correct spelling:", options: ["Seperate", "Separate", "Seprate", "Seperet"], answer: 1 },
    { question: "Identify the subject in: 'Under the tree slept the tired traveller.'", options: ["tree", "slept", "tired", "the tired traveller"], answer: 3 },
    { question: "What is the antonym of 'Arrogant'?", options: ["Proud", "Humble", "Boastful", "Stubborn"], answer: 1 },
    { question: "Complete the sentence: 'She is ______ honest woman.'", options: ["a", "an", "the", "no article"], answer: 1 },
    { question: "What is the opposite of 'Victory'?", options: ["Success", "Defeat", "Triumph", "Win"], answer: 1 },
    { question: "Choose the correct form: 'The police ______ investigating the crime.'", options: ["is", "are", "was", "has been"], answer: 1 },
    { question: "What is a narrative song or poem that tells a story called?", options: ["Ballad", "Limerick", "Sonnet", "Elegy"], answer: 0 },
    { question: "What does 'Break a leg' mean in theatre?", options: ["Get injured", "Good luck", "Quit acting", "Speak louder"], answer: 1 }
  ],

  // SCIENCE (50 QUESTIONS)
  science: [
    { question: "What gas do plants absorb for photosynthesis?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
    { question: "What is the chemical formula for water?", options: ["CO2", "O2", "H2O", "NaCl"], answer: 2 },
    { question: "Which organ in the human body pumps blood?", options: ["Brain", "Lungs", "Heart", "Liver"], answer: 2 },
    { question: "What is the boiling point of pure water at sea level?", options: ["50°C", "90°C", "100°C", "120°C"], answer: 2 },
    { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
    { question: "What is the unit of electric current?", options: ["Volt", "Watt", "Ampere", "Ohm"], answer: 2 },
    { question: "Which part of the plant conducts water from roots to leaves?", options: ["Phloem", "Xylem", "Stomata", "Chloroplast"], answer: 1 },
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Cell Wall"], answer: 2 },
    { question: "What is the center of an atom called?", options: ["Electron", "Proton", "Nucleus", "Neutron"], answer: 2 },
    { question: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], answer: 2 },
    { question: "What is the process by which a solid changes directly into a gas?", options: ["Evaporation", "Condensation", "Sublimation", "Melting"], answer: 2 },
    { question: "What is the chemical symbol for Gold?", options: ["Ag", "Au", "Fe", "Pb"], answer: 1 },
    { question: "What is the speed of light in a vacuum approximately?", options: ["300,000 km/s", "150,000 km/s", "3,000 km/s", "30,000 km/s"], answer: 0 },
    { question: "Which human organ filters waste products from the blood?", options: ["Heart", "Kidney", "Stomach", "Pancreas"], answer: 1 },
    { question: "What type of energy is stored in a stretched rubber band?", options: ["Kinetic Energy", "Potential Energy", "Thermal Energy", "Chemical Energy"], answer: 1 },
    { question: "What is the chemical symbol for Iron?", options: ["Ir", "In", "Fe", "Au"], answer: 2 },
    { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2 },
    { question: "What is the pH value of pure neutral water?", options: ["5", "7", "9", "14"], answer: 1 },
    { question: "Which vitamin is synthesized by the human body when exposed to sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answer: 3 },
    { question: "How many bones are in the adult human skeleton?", options: ["198", "206", "214", "250"], answer: 1 },
    { question: "What device is used to measure atmospheric pressure?", options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"], answer: 1 },
    { question: "Which part of the eye controls the amount of light entering it?", options: ["Retina", "Cornea", "Iris", "Lens"], answer: 2 },
    { question: "What is the green pigment in plants responsible for photosynthesis?", options: ["Chlorophyll", "Carotene", "Hemoglobin", "Melanin"], answer: 0 },
    { question: "What is the unit of force in physics?", options: ["Joule", "Pascal", "Newton", "Watt"], answer: 2 },
    { question: "Which blood type is known as the universal donor?", options: ["A+", "B-", "AB+", "O-"], answer: 3 },
    { question: "What is the chemical formula for common table salt?", options: ["NaCl", "KCl", "CaCl2", "NaHCO3"], answer: 0 },
    { question: "Which planet is the largest in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], answer: 1 },
    { question: "What force keeps the planets in orbit around the Sun?", options: ["Magnetism", "Friction", "Gravity", "Nuclear Force"], answer: 2 },
    { question: "What is the freezing point of water in Fahrenheit?", options: ["0°F", "32°F", "100°F", "212°F"], answer: 1 },
    { question: "Which organ produces insulin in the human body?", options: ["Liver", "Gallbladder", "Pancreas", "Spleen"], answer: 2 },
    { question: "Sound waves cannot travel through which of the following?", options: ["Water", "Air", "Steel", "Vacuum"], answer: 3 },
    { question: "What is the chemical symbol for Sodium?", options: ["So", "Sd", "Na", "Sm"], answer: 2 },
    { question: "Which subatomic particle has a negative electric charge?", options: ["Proton", "Neutron", "Electron", "Positron"], answer: 2 },
    { question: "What is the largest organ of the human body?", options: ["Liver", "Brain", "Skin", "Lungs"], answer: 2 },
    { question: "Which planet is closest to the Sun?", options: ["Mercury", "Venus", "Earth", "Mars"], answer: 0 },
    { question: "What type of rock is formed from cooled magma or lava?", options: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], answer: 2 },
    { question: "What is the study of living organisms called?", options: ["Geology", "Biology", "Astronomy", "Ecology"], answer: 1 },
    { question: "What is the chemical symbol for Potassium?", options: ["P", "Po", "K", "Pt"], answer: 2 },
    { question: "Which gas do humans inhale for cellular respiration?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"], answer: 1 },
    { question: "What is the SI unit of electrical resistance?", options: ["Ohm", "Volt", "Ampere", "Coulomb"], answer: 0 },
    { question: "Which celestial body is at the center of our solar system?", options: ["Earth", "The Sun", "Jupiter", "The Moon"], answer: 1 },
    { question: "What is the process of cell division in body cells called?", options: ["Mitosis", "Meiosis", "Osmosis", "Diffusion"], answer: 0 },
    { question: "Which acid is found in car batteries?", options: ["Hydrochloric Acid", "Sulfuric Acid", "Nitric Acid", "Acetic Acid"], answer: 1 },
    { question: "What is the primary function of white blood cells?", options: ["Carry oxygen", "Fight infections", "Clot blood", "Digest food"], answer: 1 },
    { question: "Which planet is famous for its prominent rings?", options: ["Mars", "Saturn", "Jupiter", "Uranus"], answer: 1 },
    { question: "What is the chemical formula for Carbon Dioxide?", options: ["CO", "CO2", "C2O", "CH4"], answer: 1 },
    { question: "What instrument is used to view microscopic objects?", options: ["Telescope", "Periscope", "Microscope", "Stethoscope"], answer: 2 },
    { question: "Which layer of the atmosphere contains the ozone layer?", options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], answer: 1 },
    { question: "What is the normal human body temperature in Celsius?", options: ["35°C", "37°C", "39°C", "40°C"], answer: 1 },
    { question: "Which animal group is warm-blooded?", options: ["Reptiles", "Amphibians", "Fish", "Mammals"], answer: 3 }
  ],

  // ART & CULTURE (50 QUESTIONS)
  art: [
    { question: "Who painted the famous artwork 'Mona Lisa'?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], answer: 2 },
    { question: "Which colors are the three Primary Colors?", options: ["Red, Green, Blue", "Red, Yellow, Blue", "Orange, Green, Purple", "Yellow, Blue, Green"], answer: 1 },
    { question: "What color do you get when you mix Red and Yellow?", options: ["Green", "Purple", "Orange", "Brown"], answer: 2 },
    { question: "Who painted 'The Starry Night'?", options: ["Vincent van Gogh", "Michelangelo", "Salvador Dali", "Rembrandt"], answer: 0 },
    { question: "What do we call a painting of inanimate objects such as fruit or flowers?", options: ["Portrait", "Landscape", "Still Life", "Abstract"], answer: 2 },
    { question: "What is the art of folding paper into decorative shapes called?", options: ["Calligraphy", "Origami", "Mosaic", "Ceramics"], answer: 1 },
    { question: "Which artistic era is famous for Michelangelo and Raphael?", options: ["Baroque", "Renaissance", "Cubism", "Surrealism"], answer: 1 },
    { question: "What type of art uses small pieces of colored glass or stone?", options: ["Collage", "Fresco", "Mosaic", "Sculpture"], answer: 2 },
    { question: "What is the lightness or darkness of a color called?", options: ["Hue", "Value", "Texture", "Saturation"], answer: 1 },
    { question: "What medium is made by mixing pigment with egg yolk?", options: ["Oil paint", "Watercolor", "Tempera", "Acrylic"], answer: 2 },
    { question: "Who sculpted the famous statue of 'David'?", options: ["Donatello", "Leonardo da Vinci", "Michelangelo", "Bernini"], answer: 2 },
    { question: "What is the term for art that does not attempt to represent external reality?", options: ["Realism", "Impressionism", "Abstract Art", "Pop Art"], answer: 2 },
    { question: "Which art movement was co-founded by Pablo Picasso and Georges Braque?", options: ["Surrealism", "Cubism", "Futurism", "Dadaism"], answer: 1 },
    { question: "Who painted 'The Last Supper'?", options: ["Raphael", "Michelangelo", "Leonardo da Vinci", "Caravaggio"], answer: 2 },
    { question: "What color is complementary (opposite) to Blue on the color wheel?", options: ["Green", "Orange", "Red", "Yellow"], answer: 1 },
    { question: "What color is complementary to Red on the color wheel?", options: ["Green", "Blue", "Purple", "Yellow"], answer: 0 },
    { question: "Who painted 'The Persistence of Memory' featuring melting clocks?", options: ["Pablo Picasso", "Salvador Dali", "Rene Magritte", "Frida Kahlo"], answer: 1 },
    { question: "What is the art of beautiful decorative handwriting called?", options: ["Typography", "Calligraphy", "Orthography", "Lithography"], answer: 1 },
    { question: "Which famous Mexican artist is celebrated for her vivid self-portraits?", options: ["Frida Kahlo", "Diego Rivera", "Georgia O'Keeffe", "Mary Cassatt"], answer: 0 },
    { question: "What is a painting executed directly upon wet plaster called?", options: ["Fresco", "Gouache", "Encaustic", "Etching"], answer: 0 },
    { question: "Which American artist was a leading figure in the Pop Art movement (Campbells Soup)?", options: ["Jackson Pollock", "Andy Warhol", "Mark Rothko", "Roy Lichtenstein"], answer: 1 },
    { question: "What is the surface on which an artist mixes colors called?", options: ["Canvas", "Palette", "Easel", "Pedestal"], answer: 1 },
    { question: "What wooden stand is used to support an artist's canvas while painting?", options: ["Easel", "Palette", "Plinth", "Armature"], answer: 0 },
    { question: "Which art technique creates an image by assembling different materials like paper and cloth?", options: ["Collage", "Engraving", "Impasto", "Sfumato"], answer: 0 },
    { question: "Who painted the Sistine Chapel ceiling in Rome?", options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Botticelli"], answer: 2 },
    { question: "What color do you get when you mix Blue and Yellow?", options: ["Green", "Purple", "Orange", "Brown"], answer: 0 },
    { question: "What color do you get when you mix Red and Blue?", options: ["Green", "Purple", "Orange", "Yellow"], answer: 1 },
    { question: "What are colors next to each other on the color wheel called?", options: ["Complementary", "Analogous", "Triadic", "Monochromatic"], answer: 1 },
    { question: "Who painted 'Girl with a Pearl Earring'?", options: ["Johannes Vermeer", "Rembrandt", "Claude Monet", "Peter Paul Rubens"], answer: 0 },
    { question: "Which style of art focuses on capturing the effects of light and everyday scenes?", options: ["Impressionism", "Baroque", "Constructivism", "Minimalism"], answer: 0 },
    { question: "Who is famous for painting Water Lilies?", options: ["Claude Monet", "Edgar Degas", "Paul Cezanne", "Pierre-Auguste Renoir"], answer: 0 },
    { question: "What is the technique of applying thick paint that stands out from the surface called?", options: ["Glazing", "Impasto", "Grisaille", "Chiaroscuro"], answer: 1 },
    { question: "What is the contrast between light and dark in art called?", options: ["Sfumato", "Chiaroscuro", "Tenebrism", "Hatching"], answer: 1 },
    { question: "Which famous sculpture depicts a woman with no arms at the Louvre Museum?", options: ["Venus de Milo", "Winged Victory", "Pietà", "The Thinker"], answer: 0 },
    { question: "Who sculpted 'The Thinker'?", options: ["Auguste Rodin", "Michelangelo", "Alberto Giacometti", "Henry Moore"], answer: 0 },
    { question: "What is the primary material used in ceramic sculpture?", options: ["Clay", "Plaster", "Bronze", "Wood"], answer: 0 },
    { question: "Which culture is famous for Terracotta Army sculptures?", options: ["Egypt", "Greece", "China", "Rome"], answer: 2 },
    { question: "What type of perspective creates the illusion of depth using a vanishing point?", options: ["Linear Perspective", "Atmospheric Perspective", "Isometric Perspective", "Curvilinear Perspective"], answer: 0 },
    { question: "What is a color mixed with white called?", options: ["Shade", "Tone", "Tint", "Hue"], answer: 2 },
    { question: "What is a color mixed with black called?", options: ["Shade", "Tone", "Tint", "Value"], answer: 0 },
    { question: "Who painted 'Guernica', depicting the tragedies of war?", options: ["Pablo Picasso", "Francisco Goya", "Salvador Dali", "Henri Matisse"], answer: 0 },
    { question: "Which artistic movement celebrated industrial machinery and speed?", options: ["Futurism", "Romanticism", "Rococo", "Art Nouveau"], answer: 0 },
    { question: "What is the Japanese art of flower arrangement called?", options: ["Ikebana", "Bonsai", "Origami", "Ukiyo-e"], answer: 0 },
    { question: "What does 'Monochromatic' mean in art?", options: ["Many vibrant colors", "Variations of a single hue", "Black and white only", "Warm colors only"], answer: 1 },
    { question: "Who painted 'The Scream'?", options: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Paul Gauguin"], answer: 0 },
    { question: "Who painted 'The Kiss' featuring golden patterns?", options: ["Gustav Klimt", "Alphonse Mucha", "Henri de Toulouse-Lautrec", "Paul Klee"], answer: 0 },
    { question: "Which art style features ornate, flowing curves inspired by plant forms?", options: ["Art Nouveau", "Bauhaus", "Minimalism", "Constructivism"], answer: 0 },
    { question: "What is the term for a rapid drawing capturing the basic form of a subject?", options: ["Sketch", "Engraving", "Fresco", "Lithograph"], answer: 0 },
    { question: "Which famous museum houses the Mona Lisa?", options: ["The Met (New York)", "The Louvre (Paris)", "The Prado (Madrid)", "British Museum (London)"], answer: 1 },
    { question: "What is a three-dimensional work of art created by shaping or carving called?", options: ["Sculpture", "Mural", "Print", "Mosaic"], answer: 0 }
  ],

  // CURRENT AFFAIRS (50 QUESTIONS)
  current_affairs: [
    { question: "Who is the current Secretary-General of the United Nations (UN)?", options: ["Ban Ki-moon", "António Guterres", "Kofi Annan", "Tedros Adhanom"], answer: 1 },
    { question: "Which country hosted the Olympic Games in 2024?", options: ["Japan", "USA", "France (Paris)", "United Kingdom"], answer: 2 },
    { question: "What is the official currency of the United Kingdom?", options: ["Euro", "Dollar", "Pound Sterling", "Yen"], answer: 2 },
    { question: "Which continent has the largest human population in the world?", options: ["Africa", "Asia", "Europe", "North America"], answer: 1 },
    { question: "What is the capital city of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
    { question: "What does the abbreviation 'WHO' stand for?", options: ["World Health Organization", "World Housing Office", "World Heritage Order", "Wide Health Operations"], answer: 0 },
    { question: "Which organization was awarded the Nobel Peace Prize in 2020?", options: ["UNICEF", "World Food Programme", "Red Cross", "Doctors Without Borders"], answer: 1 },
    { question: "What is the longest river in Africa?", options: ["River Niger", "River Congo", "River Nile", "River Zambezi"], answer: 2 },
    { question: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], answer: 3 },
    { question: "Which country has the largest land area in the world?", options: ["Canada", "China", "Russia", "United States"], answer: 2 },
    { question: "What is the headquarters location of the United Nations (UN)?", options: ["Geneva", "New York City", "Paris", "London"], answer: 1 },
    { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Ringgit"], answer: 2 },
    { question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "South Korea", "Thailand"], answer: 1 },
    { question: "Who is the current President of the World Bank Group (appointed 2023)?", options: ["Ajay Banga", "David Malpass", "Jim Yong Kim", "Kristalina Georgieva"], answer: 0 },
    { question: "What is the capital city of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3 },
    { question: "What does 'NATO' stand for?", options: ["North Atlantic Treaty Organization", "National American Trade Office", "North Asian Transport Order", "National Alliance for Technical Operations"], answer: 0 },
    { question: "Which country won the FIFA Men's World Cup in 2022?", options: ["France", "Brazil", "Argentina", "Croatia"], answer: 2 },
    { question: "What is the currency of the European Union member states?", options: ["Pound", "Euro", "Franc", "Krona"], answer: 1 },
    { question: "Which is the smallest country in the world by land area?", options: ["Monaco", "Nauru", "Vatican City", "San Marino"], answer: 2 },
    { question: "What is the capital of Nigeria?", options: ["Lagos", "Abuja", "Kano", "Port Harcourt"], answer: 1 },
    { question: "What is the official currency of Nigeria?", options: ["Naira", "Cedi", "Rand", "Shilling"], answer: 0 },
    { question: "What does 'OPEC' stand for?", options: ["Organization of Petroleum Exporting Countries", "Oil Production and Energy Council", "Overseas Petroleum Exploration Committee", "Oil Producers Economic Coalition"], answer: 0 },
    { question: "What is the capital city of Germany?", options: ["Munich", "Frankfurt", "Berlin", "Hamburg"], answer: 2 },
    { question: "Which country left the European Union in the process known as 'Brexit'?", options: ["France", "United Kingdom", "Germany", "Italy"], answer: 1 },
    { question: "Who was the first female Prime Minister of the United Kingdom?", options: ["Theresa May", "Margaret Thatcher", "Liz Truss", "Angela Merkel"], answer: 1 },
    { question: "What is the capital of South Africa?", options: ["Johannesburg", "Pretoria", "Durban", "Cape Town & Pretoria"], answer: 3 },
    { question: "Which African country is known as the 'Giant of Africa'?", options: ["South Africa", "Egypt", "Nigeria", "Ghana"], answer: 2 },
    { question: "What is the capital city of Ghana?", options: ["Kumasi", "Accra", "Tamale", "Cape Coast"], answer: 1 },
    { question: "What is the currency of Ghana?", options: ["Naira", "Cedi", "Rand", "Kwacha"], answer: 1 },
    { question: "What does 'ECOWAS' stand for?", options: ["Economic Community of West African States", "East Coast Oil and Water Authority", "Energy Cooperation of West African Sector", "Economic Council of Western Associated States"], answer: 0 },
    { question: "Where are the headquarters of the African Union (AU) located?", options: ["Addis Ababa (Ethiopia)", "Cairo (Egypt)", "Nairobi (Kenya)", "Abuja (Nigeria)"], answer: 0 },
    { question: "What is the capital city of Kenya?", options: ["Mombasa", "Nairobi", "Kisumu", "Eldoret"], answer: 1 },
    { question: "Which canal connects the Mediterranean Sea to the Red Sea?", options: ["Panama Canal", "Suez Canal", "Kiel Canal", "Erie Canal"], answer: 1 },
    { question: "Which canal connects the Atlantic Ocean to the Pacific Ocean?", options: ["Suez Canal", "Panama Canal", "Corinth Canal", "Welland Canal"], answer: 1 },
    { question: "What is the capital city of Japan?", options: ["Kyoto", "Osaka", "Tokyo", "Hiroshima"], answer: 2 },
    { question: "What is the capital of Egypt?", options: ["Alexandria", "Cairo", "Giza", "Luxor"], answer: 1 },
    { question: "Who was the first President of the United States?", options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], answer: 1 },
    { question: "Who was the first black President of South Africa?", options: ["Thabo Mbeki", "Nelson Mandela", "Jacob Zuma", "Cyril Ramaphosa"], answer: 1 },
    { question: "What is the currency of China?", options: ["Yen", "Renminbi (Yuan)", "Won", "Baht"], answer: 1 },
    { question: "What is the capital city of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], answer: 2 },
    { question: "What is the capital city of India?", options: ["Mumbai", "New Delhi", "Kolkata", "Bangalore"], answer: 1 },
    { question: "What does 'UNESCO' stand for?", options: ["UN Educational, Scientific and Cultural Organization", "UN Economic and Social Care Order", "UN Environmental and Sanitation Council", "UN Emergency School Cooperation Office"], answer: 0 },
    { question: "Which country has the highest number of official languages?", options: ["India", "South Africa", "Bolivia", "Papua New Guinea"], answer: 2 },
    { question: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Valencia", "Seville"], answer: 1 },
    { question: "What is the capital city of Italy?", options: ["Milan", "Venice", "Rome", "Naples"], answer: 2 },
    { question: "Which country is the largest economy in the world by nominal GDP?", options: ["China", "United States", "Japan", "Germany"], answer: 1 },
    { question: "What is the currency of the United States?", options: ["US Dollar", "Pound", "Euro", "Peso"], answer: 0 },
    { question: "Which planet in our solar system is nicknamed the Morning Star?", options: ["Mars", "Venus", "Jupiter", "Saturn"], answer: 1 },
    { question: "How many countries are permanent members of the UN Security Council?", options: ["3", "5", "7", "10"], answer: 1 },
    { question: "What international award is presented annually for physics, chemistry, medicine, and peace?", options: ["Pulitzer Prize", "Nobel Prize", "Academy Award", "Grammy Award"], answer: 1 }
  ],

  // GENERAL KNOWLEDGE & COMPUTER SCIENCE (50 QUESTIONS)
  general_knowledge: [
    { question: "What does HTML stand for in web development?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlink and Text Management Language", "Home Tool Markup Language"], answer: 0 },
    { question: "Which company developed the Android operating system?", options: ["Apple", "Google", "Microsoft", "Samsung"], answer: 1 },
    { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
    { question: "Which device is used to input text into a computer?", options: ["Monitor", "Mouse", "Keyboard", "Printer"], answer: 2 },
    { question: "What is the capital city of France?", options: ["Rome", "Berlin", "Paris", "Madrid"], answer: 2 },
    { question: "Which company created ChatGPT?", options: ["Google", "Microsoft", "OpenAI", "Meta"], answer: 2 },
    { question: "What is the main function of RAM in a computer?", options: ["Permanent storage", "Temporary fast memory", "Cooling the processor", "Connecting to internet"], answer: 1 },
    { question: "What does 'WWW' stand for?", options: ["World Wide Web", "Wide World Words", "Web World Wide", "Wireless Web Works"], answer: 0 },
    { question: "How many sides does an Octagon have?", options: ["6", "7", "8", "10"], answer: 2 },
    { question: "Which is the tallest mountain in the world above sea level?", options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Mount Fuji"], answer: 2 },
    { question: "What does 'CPU' stand for in computer hardware?", options: ["Central Processing Unit", "Computer Program Unit", "Core Power Utility", "Central Performance Unit"], answer: 0 },
    { question: "What does 'URL' stand for?", options: ["Uniform Resource Locator", "Universal Reference Link", "Unified Routing Language", "Universal Record Line"], answer: 0 },
    { question: "Which key on a keyboard is used to create space between words?", options: ["Backspace", "Enter", "Spacebar", "Shift"], answer: 2 },
    { question: "How many bits are in one Byte?", options: ["4", "8", "16", "32"], answer: 1 },
    { question: "How many Megabytes (MB) are in 1 Gigabyte (GB)?", options: ["100", "500", "1000", "1024"], answer: 3 },
    { question: "What does 'HTTP' stand for in web browsers?", options: ["HyperText Transfer Protocol", "High Transfer Tech Program", "Hyper Terminal Text Port", "Home Tool Transport Protocol"], answer: 0 },
    { question: "What does the 'S' stand for in 'HTTPS'?", options: ["Speed", "Secure", "Server", "System"], answer: 1 },
    { question: "Which programming language is predominantly used to add interactivity to web pages?", options: ["HTML", "CSS", "JavaScript", "SQL"], answer: 2 },
    { question: "What does 'SQL' stand for in database management?", options: ["Structured Query Language", "Simple Quick Logic", "System Query Link", "Standard Question Language"], answer: 0 },
    { question: "Who is widely considered the father of modern computing?", options: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], answer: 1 },
    { question: "Who was the first computer programmer in history?", options: ["Ada Lovelace", "Grace Hopper", "Katherine Johnson", "Margaret Hamilton"], answer: 0 },
    { question: "Which company created the Windows operating system?", options: ["Apple", "IBM", "Microsoft", "Intel"], answer: 2 },
    { question: "What is the primary language of iOS app development?", options: ["Java", "Swift", "C#", "Kotlin"], answer: 1 },
    { question: "What is the primary language used for native Android development?", options: ["Kotlin / Java", "Swift", "PHP", "Ruby"], answer: 0 },
    { question: "What does 'PDF' stand for?", options: ["Portable Document Format", "Public Data File", "Personal Document Folder", "Program Data File"], answer: 0 },
    { question: "Which shortcut key is commonly used to copy selected text on Windows?", options: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"], answer: 1 },
    { question: "Which shortcut key is used to paste copied text on Windows?", options: ["Ctrl + P", "Ctrl + V", "Ctrl + S", "Ctrl + A"], answer: 1 },
    { question: "Which shortcut key is used to undo an action on Windows?", options: ["Ctrl + U", "Ctrl + Y", "Ctrl + Z", "Ctrl + W"], answer: 2 },
    { question: "What type of software is designed to harm or exploit computers?", options: ["Freeware", "Malware", "Shareware", "Firmware"], answer: 1 },
    { question: "What does 'Wi-Fi' stand for?", options: ["Wireless Fidelity", "Wide Field", "Wire Free Internet", "Wireless Flow"], answer: 0 },
    { question: "What is the physical board inside a computer that connects all components?", options: ["Hard Drive", "Motherboard", "Sound Card", "Graphics Card"], answer: 1 },
    { question: "What does 'SSD' stand for in storage drives?", options: ["Solid State Drive", "Super Speed Disk", "System Storage Device", "Secure State Drive"], answer: 0 },
    { question: "What is the smallest unit of digital image data on a display screen?", options: ["Byte", "Pixel", "Dot", "Voxel"], answer: 1 },
    { question: "What does 'LAN' stand for in networking?", options: ["Local Area Network", "Large Access Node", "Linked Audio Network", "Local Array Node"], answer: 0 },
    { question: "What is the standard port for HTTP web traffic?", options: ["21", "22", "80", "443"], answer: 2 },
    { question: "What is the standard port for HTTPS encrypted web traffic?", options: ["25", "80", "443", "8080"], answer: 2 },
    { question: "What does 'GUI' stand for in computing?", options: ["Graphical User Interface", "General User Interaction", "Global Utility Interface", "Graphic Universal Index"], answer: 0 },
    { question: "What type of computer network spans across cities, countries, or the globe?", options: ["LAN", "PAN", "WAN", "SAN"], answer: 2 },
    { question: "What is an open-source version control system created by Linus Torvalds?", options: ["Git", "SVN", "Mercurial", "Docker"], answer: 0 },
    { question: "What is the world's most popular web search engine?", options: ["Bing", "Yahoo", "Google", "DuckDuckGo"], answer: 2 },
    { question: "Who founded Microsoft along with Paul Allen in 1975?", options: ["Steve Jobs", "Bill Gates", "Jeff Bezos", "Elon Musk"], answer: 1 },
    { question: "Who co-founded Apple Inc. alongside Steve Wozniak?", options: ["Steve Jobs", "Tim Cook", "Larry Page", "Mark Zuckerberg"], answer: 0 },
    { question: "Which company owns the social media platforms Facebook, Instagram, and WhatsApp?", options: ["Alphabet", "Meta", "Amazon", "Twitter"], answer: 1 },
    { question: "What does 'AI' stand for?", options: ["Automated Internet", "Artificial Intelligence", "Advanced Integration", "App Interface"], answer: 1 },
    { question: "What does 'IoT' stand for in modern technology?", options: ["Internet of Things", "Index of Tech", "Integrated Online Tasks", "Internal Operations Team"], answer: 0 },
    { question: "Which symbol is used in JavaScript to check both value and type equality?", options: ["=", "==", "===", "!="], answer: 2 },
    { question: "What is the primary function of an operating system?", options: ["Play games", "Manage hardware and software resources", "Edit photos", "Browse websites"], answer: 1 },
    { question: "What is the cloud computing service platform provided by Amazon?", options: ["Azure", "Google Cloud", "AWS (Amazon Web Services)", "iCloud"], answer: 2 },
    { question: "What does 'CSS' stand for in web styling?", options: ["Cascading Style Sheets", "Creative Style System", "Computer Styling Syntax", "Colorful Style Sheets"], answer: 0 },
    { question: "Which browser is developed and maintained by Google?", options: ["Safari", "Firefox", "Chrome", "Edge"], answer: 2 }
  ]
};

// Shuffle function
function shuffleQuestions(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const randomIndex = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[randomIndex]] = [shuffled[randomIndex], shuffled[i]];
  }
  return shuffled;
}

// Make accessible globally
window.subjectQuestions = subjectQuestions;
window.shuffleQuestions = shuffleQuestions;
